version: '3.5'
services:
  vantiq-edge:
    #Specify Vantiq image version, contact Vanitq for access to docker hub.
    image: vantiq/vantiq-edge:1.30-SNAPSHOT 
    depends_on:
    - vantiq_edge_mongo
    ports:
    #Ports default to 8080 but can be changed.
    - 8080:8080
    restart: unless-stopped
    volumes:
    #License files are provided by Vantiq Support.
    - ./public.pem:/opt/vantiq/config/public.pem
    - ./license.key:/opt/vantiq/config/license.key
    networks:
      vantiq-edge:
        aliases: []
  vantiq_edge_mongo:
    #Mongo is required by Vantiq for storage. 
    image: bitnami/mongodb:4.0.3
    restart: unless-stopped
    environment:
    - MONGODB_USERNAME=<default username>
    - MONGODB_PASSWORD=<default password>
    - MONGODB_DATABASE=<default database name>
    volumes:
    - vantiq_edge_data:/bitnami:rw
    networks:
      vantiq-edge:
        aliases: []        
networks:
  vantiq-edge:
    ipam:
      config: []      
volumes:
  vantiq_edge_data: {}
