version: '3.5'
services:
  vantiq-edge:
    image: pburma/varmtest:latest
    links: 
    - "vantiq_edge_mongo:vantiq_edge_mongo"     
    depends_on:
    - vantiq_edge_mongo
    ports:
    - 8080:8080
    restart: unless-stopped
    volumes:
    - ./public.pem:/opt/vantiq/config/public.pem
    - ./license.key:/opt/vantiq/config/license.key
  vantiq_edge_mongo:
    image: bitnami/mongodb:4.0.3
    restart: unless-stopped
    environment:
    - MONGODB_USERNAME=<default username>
    - MONGODB_PASSWORD=<default password>
    - MONGODB_DATABASE=<default db name>
    volumes:
    - vantiq_edge_data:/bitnami:rw      
  vantiq_edge_timescale:
    image: timescale/timescaledb:latest-pg12
    ports:
    - 5432:5432
    environment:
    - POSTGRES_DB=app_db
    - POSTGRES_USER=app_user
    - POSTGRES_PASSWORD=password  
    volumes:
    - vantiq_edge_timescale:/var/lib/postgresql/data:rw     
  vantiq_edge_postgrest:
    image: postgrest/postgrest
    ports:
    - 3000:3000
    environment:
      PGRST_DB_URI: postgres://app_user:password@vantiq_edge_timescale:5432/app_db
      PGRST_DB_SCHEMA: public
      PGRST_DB_ANON_ROLE: app_user #In production this role should not be the same as the one used for the connection
      PGRST_OPENAPI_SERVER_PROXY_URI: http://127.0.0.1:3000
    depends_on:
      - vantiq_edge_timescale  
volumes:
  vantiq_edge_data: {}
  vantiq_edge_timescale: {}