version: '3.5'
services:
  vantiq-edge:
    image: vantiq/vantiq-edge:1.30-SNAPSHOT
    depends_on:
    - vantiq_edge_mongo
    ports:
    - 8080:8080
    restart: unless-stopped
    volumes:
    - ./public.pem:/opt/vantiq/config/public.pem
    - ./license.key:/opt/vantiq/config/license.key
    - ./webUIConfig.json:/opt/vantiq/config/webUIConfig.json
    - ./brandedProperties:/opt/vantiq/config/brandedProperties
    - ./myAppIcon.png:/opt/vantiq/config/myAppIcon.png
    - ./myNavbarIcon.png:/opt/vantiq/config/myNavbarIcon.png
    networks:
      vantiq-edge:
        aliases: []
  vantiq_edge_mongo:
    image: bitnami/mongodb:4.0.3
    restart: unless-stopped
    environment:
    - MONGODB_USERNAME=<default username>
    - MONGODB_PASSWORD=<default password>
    - MONGODB_DATABASE=<default database name>
    volumes:
    - vantiq_edge_data:/bitnami:rw
    networks:
      vantiq-edge:
        aliases: []        
networks:
  vantiq-edge:
    ipam:
      config: []      
volumes:
  vantiq_edge_data: {}
