version: '3.5'
services:
  vantiq-edge:
    image: quay.io/vantiq/vantiq-edge:1.30-SNAPSHOT  
    depends_on:
    - vantiq_edge_mongo
    ports:
    - 8080:8080
    restart: unless-stopped
    volumes:
    - ./public.pem:/opt/vantiq/config/public.pem
    - ./license.key:/opt/vantiq/config/license.key
    networks:
    - vantiq-edge
  vantiq_edge_mongo:
    image: quay.io/pburma/extension-sources:mdbsj-1.0
    restart: unless-stopped
    environment:
    - MONGODB_USERNAME=ars
    - MONGODB_PASSWORD=ars
    - MONGODB_DATABASE=ars02
    volumes:
    - vantiq_edge_data:/bitnami:rw   
    networks: 
    - vantiq-edge    
networks:
  vantiq-edge:  {} 
volumes:
  vantiq_edge_data: {}