version: '3.5'
services:
  vantiq-edge:
    image: quay.io/vantiq/vantiq-edge:1.30-SNAPSHOT  
    depends_on:
    - vantiq_edge_mongo
    ports:
    - 8080:8080
    restart: unless-stopped
    volumes:
    - ./public.pem:/opt/vantiq/config/public.pem
    - ./license.key:/opt/vantiq/config/license.key
    networks:
    - vantiq-edge
  vantiq_edge_mongo:
    image: bitnami/mongodb:4.0.3
    restart: unless-stopped
    environment:
    - MONGODB_USERNAME=ars
    - MONGODB_PASSWORD=ars
    - MONGODB_DATABASE=ars02
    volumes:
    - vantiq_edge_data:/bitnami:rw   
    - ./mongodump_ars02:/docker-entrypoint-initdb.d/mongodump_ars02
    - ./initdb.sh:/docker-entrypoint-initdb.d/initdb.sh
    networks: 
    - vantiq-edge    
networks:
  vantiq-edge:  {} 
volumes:
  vantiq_edge_data: {}